#
# Run this script in Git Bash on Windows to restore .go files and remove
# the clump.go file generated by the windows-clump-files.sh script.
#
if test ! -d ds3/models ; then
   echo Run this from the root directory.
   exit 1
fi

test -f ds3/models/clump.go && echo 'Removing clump.go' && rm ds3/models/clump.go

COUNT=$((find ds3/models -name *.go.orig  | 
    while read F ; do
       echo $F
       OLDF=`echo $F | sed 's/.orig$//'`
       mv $F $OLDF
     done) | wc -l)

if [[ $COUNT -eq 0 ]] ; then 
    echo No files were restored.
else
    echo $COUNT files were restored.
fi
