#!/bin/bash

# Generates the documentation for the SDK and places the documentation
# in a version specific folder.

if [ -z "$1" ]; then
    echo "Usage: $0 <SDK-Version>"
    exit 1
fi

VERSION=$1

echo "Generating documentation for Go SDK version ${VERSION}"

mkdir $VERSION
cd $VERSION

# Host the SDK documentation locally using godoc
godoc -http=localhost:8080

# Get all the static docs generated by godoc
# -r downloads files recursively
# -np does not ascend to the parent directory
# -N only retrieves files if newer than local
# -E adds extension .html to html files if they do not have extension
# -p downloads all files for each page, including css, js, and images
# -k converts links to relative paths
# -nH does not generate host prefix directory (i.e. no localhost:8080 folder)
# --cut-dirs=1 does not generate the first layer of folders
wget -r -np -N -E -p -k -nH --cut-dirs=1 http://localhost:8080/pkg/
